name: ngsplusapp
description: NGS Plus Yoklama Takip Sistemi - QR kod tabanlı modern yoklama uygulaması
version: 1.0.0+1

environment:
  sdk: '^3.8.0'
  flutter: ">=3.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Supabase integration
  supabase_flutter: ^2.5.6
  
  # QR Code scanning
  mobile_scanner: ^5.0.0
  
  # QR Code generation
  qr_flutter: ^4.1.0
  
  # Local storage
  shared_preferences: ^2.2.3
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # HTTP requests
  http: ^1.2.1
  
  # Internationalization
  intl: ^0.20.2
  
  # Fonts
  google_fonts: ^6.2.1
  
  # SVG support
  flutter_svg: ^2.0.10+1
  
  # Permissions
  permission_handler: ^11.3.1
  
  # State management
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - .env
    - assets/images/
    # Assets klasörleri oluşturuldukça eklenebilir:
    # - assets/icons/

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ngs_app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#a0002a"
  adaptive_icon_foreground: "assets/images/ngs_app_icon.png"
  remove_alpha_ios: true 